version: '3'
services:
    postgres:
        image: postgres:10
        ports: 
            - 5432:5432
        volumes:
            - ./dev-db/postgres-scripts:/docker-entrypoint-initdb.d
            - ./dev-db/flyway-5.2.4:/flyway
            - ./src/migrations/flyway:/flyway/sql
        environment:
            POSTGRES_DB: interesne-dejavnosti
    maildev:
        image: djfarrelly/maildev
        command: bin/maildev --web 8025 --smtp 1025 --hide-extensions STARTTLS
        ports:
            - '8025:8025'
            - '1025:1025'
