/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.activity_id_seq</code>
     */
    public static final Sequence<Long> ACTIVITY_ID_SEQ = new SequenceImpl<Long>("activity_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.activity_log_id_seq</code>
     */
    public static final Sequence<Long> ACTIVITY_LOG_ID_SEQ = new SequenceImpl<Long>("activity_log_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.authorized_companion_id_seq</code>
     */
    public static final Sequence<Integer> AUTHORIZED_COMPANION_ID_SEQ = new SequenceImpl<Integer>("authorized_companion_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.error_log_id_seq</code>
     */
    public static final Sequence<Long> ERROR_LOG_ID_SEQ = new SequenceImpl<Long>("error_log_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.pupil_id_seq</code>
     */
    public static final Sequence<Long> PUPIL_ID_SEQ = new SequenceImpl<Long>("pupil_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
