/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db;


import javax.annotation.Generated;

import si.francebevk.db.tables.Pupil;
import si.francebevk.db.tables.PupilGroup;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Contains a single pupil
     */
    public static final Pupil PUPIL = si.francebevk.db.tables.Pupil.PUPIL;

    /**
     * A class of pupils
     */
    public static final PupilGroup PUPIL_GROUP = si.francebevk.db.tables.PupilGroup.PUPIL_GROUP;
}
