/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db;


import javax.annotation.Generated;

import si.francebevk.db.udt.NamedStrings;
import si.francebevk.db.udt.TimeSlot;


/**
 * Convenience access to all UDTs in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UDTs {

    /**
     * The type <code>public.named_strings</code>
     */
    public static NamedStrings NAMED_STRINGS = si.francebevk.db.udt.NamedStrings.NAMED_STRINGS;

    /**
     * The type <code>public.time_slot</code>
     */
    public static TimeSlot TIME_SLOT = si.francebevk.db.udt.TimeSlot.TIME_SLOT;
}
