/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;

import si.francebevk.db.enums.ActivityLogType;
import si.francebevk.db.tables.ActivityLog;


/**
 * Records the activity related to a pupil
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityLogRecord extends UpdatableRecordImpl<ActivityLogRecord> implements Record6<Long, Long, OffsetDateTime, Boolean, ActivityLogType, String> {

    private static final long serialVersionUID = -1495565475;

    /**
     * Setter for <code>public.activity_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.activity_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.activity_log.pupil_id</code>. ID of the pupil to whom this log entry applies
     */
    public void setPupilId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.activity_log.pupil_id</code>. ID of the pupil to whom this log entry applies
     */
    public Long getPupilId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.activity_log.time</code>. The time at which the event happened
     */
    public void setTime(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.activity_log.time</code>. The time at which the event happened
     */
    public OffsetDateTime getTime() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.activity_log.admin_user</code>. True when the action was performed by an admin user, not the parent
     */
    public void setAdminUser(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.activity_log.admin_user</code>. True when the action was performed by an admin user, not the parent
     */
    public Boolean getAdminUser() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.activity_log.type</code>. What actually happened?
     */
    public void setType(ActivityLogType value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.activity_log.type</code>. What actually happened?
     */
    public ActivityLogType getType() {
        return (ActivityLogType) get(4);
    }

    /**
     * Setter for <code>public.activity_log.details</code>. A description of the event that we can display when reconstructing events
     */
    public void setDetails(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.activity_log.details</code>. A description of the event that we can display when reconstructing events
     */
    public String getDetails() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, OffsetDateTime, Boolean, ActivityLogType, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Long, Long, OffsetDateTime, Boolean, ActivityLogType, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ActivityLog.ACTIVITY_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ActivityLog.ACTIVITY_LOG.PUPIL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field3() {
        return ActivityLog.ACTIVITY_LOG.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return ActivityLog.ACTIVITY_LOG.ADMIN_USER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ActivityLogType> field5() {
        return ActivityLog.ACTIVITY_LOG.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return ActivityLog.ACTIVITY_LOG.DETAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getPupilId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component3() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getAdminUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogType component5() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPupilId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value3() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getAdminUser();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogType value5() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDetails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogRecord value2(Long value) {
        setPupilId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogRecord value3(OffsetDateTime value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogRecord value4(Boolean value) {
        setAdminUser(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogRecord value5(ActivityLogType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogRecord value6(String value) {
        setDetails(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivityLogRecord values(Long value1, Long value2, OffsetDateTime value3, Boolean value4, ActivityLogType value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityLogRecord
     */
    public ActivityLogRecord() {
        super(ActivityLog.ACTIVITY_LOG);
    }

    /**
     * Create a detached, initialised ActivityLogRecord
     */
    public ActivityLogRecord(Long id, Long pupilId, OffsetDateTime time, Boolean adminUser, ActivityLogType type, String details) {
        super(ActivityLog.ACTIVITY_LOG);

        set(0, id);
        set(1, pupilId);
        set(2, time);
        set(3, adminUser);
        set(4, type);
        set(5, details);
    }
}
