/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;

import si.francebevk.db.tables.ErrorLog;


/**
 * Contains errors that may have happened during the process
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ErrorLogRecord extends UpdatableRecordImpl<ErrorLogRecord> implements Record4<Long, Long, OffsetDateTime, String> {

    private static final long serialVersionUID = 456378814;

    /**
     * Setter for <code>public.error_log.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.error_log.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.error_log.pupil_id</code>. Id of the pupil to which the error happened
     */
    public void setPupilId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.error_log.pupil_id</code>. Id of the pupil to which the error happened
     */
    public Long getPupilId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.error_log.created_on</code>. The timestamp on which the error happened
     */
    public void setCreatedOn(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.error_log.created_on</code>. The timestamp on which the error happened
     */
    public OffsetDateTime getCreatedOn() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.error_log.message</code>. The error message
     */
    public void setMessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.error_log.message</code>. The error message
     */
    public String getMessage() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, OffsetDateTime, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, OffsetDateTime, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ErrorLog.ERROR_LOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ErrorLog.ERROR_LOG.PUPIL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field3() {
        return ErrorLog.ERROR_LOG.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ErrorLog.ERROR_LOG.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getPupilId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component3() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getPupilId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value3() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ErrorLogRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ErrorLogRecord value2(Long value) {
        setPupilId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ErrorLogRecord value3(OffsetDateTime value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ErrorLogRecord value4(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ErrorLogRecord values(Long value1, Long value2, OffsetDateTime value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ErrorLogRecord
     */
    public ErrorLogRecord() {
        super(ErrorLog.ERROR_LOG);
    }

    /**
     * Create a detached, initialised ErrorLogRecord
     */
    public ErrorLogRecord(Long id, Long pupilId, OffsetDateTime createdOn, String message) {
        super(ErrorLog.ERROR_LOG);

        set(0, id);
        set(1, pupilId);
        set(2, createdOn);
        set(3, message);
    }
}
