/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import si.francebevk.db.tables.Pupil;


/**
 * Contains a single pupil
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PupilRecord extends UpdatableRecordImpl<PupilRecord> {

    private static final long serialVersionUID = 1375964999;

    /**
     * Setter for <code>public.pupil.id</code>. The pupil's unique ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pupil.id</code>. The pupil's unique ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pupil.pupil_group</code>. The pupil's class
     */
    public void setPupilGroup(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pupil.pupil_group</code>. The pupil's class
     */
    public String getPupilGroup() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pupil.access_code</code>. The pupil's access code required to access their profile
     */
    public void setAccessCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pupil.access_code</code>. The pupil's access code required to access their profile
     */
    public String getAccessCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.pupil.extended_stay</code>. Indicates choice for pupil's inclusion in extended stay
     */
    public void setExtendedStay(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pupil.extended_stay</code>. Indicates choice for pupil's inclusion in extended stay
     */
    public Boolean getExtendedStay() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.pupil.leave_mon</code>. Indicates the minutes of day at which pupil will leave school on monday (null means student is not participating on that day)
     */
    public void setLeaveMon(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pupil.leave_mon</code>. Indicates the minutes of day at which pupil will leave school on monday (null means student is not participating on that day)
     */
    public Short getLeaveMon() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.pupil.leave_tue</code>. Indicates the minutes of day at which pupil will leave school on tuesday (null means student is not participating on that day)
     */
    public void setLeaveTue(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pupil.leave_tue</code>. Indicates the minutes of day at which pupil will leave school on tuesday (null means student is not participating on that day)
     */
    public Short getLeaveTue() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.pupil.leave_wed</code>. Indicates the minutes of day at which pupil will leave school on wednesday (null means student is not participating on that day)
     */
    public void setLeaveWed(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pupil.leave_wed</code>. Indicates the minutes of day at which pupil will leave school on wednesday (null means student is not participating on that day)
     */
    public Short getLeaveWed() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.pupil.leave_thu</code>. Indicates the minutes of day at which pupil will leave school on thursday (null means student is not participating on that day)
     */
    public void setLeaveThu(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.pupil.leave_thu</code>. Indicates the minutes of day at which pupil will leave school on thursday (null means student is not participating on that day)
     */
    public Short getLeaveThu() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>public.pupil.leave_fri</code>. Indicates the minutes of day at which pupil will leave school on friday (null means student is not participating on that day)
     */
    public void setLeaveFri(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.pupil.leave_fri</code>. Indicates the minutes of day at which pupil will leave school on friday (null means student is not participating on that day)
     */
    public Short getLeaveFri() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>public.pupil.last_login</code>.
     */
    public void setLastLogin(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.pupil.last_login</code>.
     */
    public OffsetDateTime getLastLogin() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.pupil.emails</code>. All the emails to which messages for this pupil should be sent
     */
    public void setEmails(String... value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.pupil.emails</code>. All the emails to which messages for this pupil should be sent
     */
    public String[] getEmails() {
        return (String[]) get(10);
    }

    /**
     * Setter for <code>public.pupil.welcome_email_sent</code>. Set to true once an email was successfuly sent to this pupil
     */
    public void setWelcomeEmailSent(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.pupil.welcome_email_sent</code>. Set to true once an email was successfuly sent to this pupil
     */
    public Boolean getWelcomeEmailSent() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.pupil.first_name</code>. First name of the pupil
     */
    public void setFirstName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.pupil.first_name</code>. First name of the pupil
     */
    public String getFirstName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.pupil.last_name</code>. Last name of the pupil
     */
    public void setLastName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.pupil.last_name</code>. Last name of the pupil
     */
    public String getLastName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.pupil.can_leave_alone</code>. If true, younger pupils can still leave school without an escort
     */
    public void setCanLeaveAlone(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.pupil.can_leave_alone</code>. If true, younger pupils can still leave school without an escort
     */
    public Boolean getCanLeaveAlone() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.pupil.morning_care_arrival</code>. If not null then the pupil will arrive into morning care at this time
     */
    public void setMorningCareArrival(Short value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.pupil.morning_care_arrival</code>. If not null then the pupil will arrive into morning care at this time
     */
    public Short getMorningCareArrival() {
        return (Short) get(15);
    }

    /**
     * Setter for <code>public.pupil.order_textbooks</code>. Did the pupil order textbooks from the school's textbook fund?
     */
    public void setOrderTextbooks(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.pupil.order_textbooks</code>. Did the pupil order textbooks from the school's textbook fund?
     */
    public Boolean getOrderTextbooks() {
        return (Boolean) get(16);
    }

    /**
     * Setter for <code>public.pupil.morning_snack_mon</code>.
     */
    public void setMorningSnackMon(Boolean value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.pupil.morning_snack_mon</code>.
     */
    public Boolean getMorningSnackMon() {
        return (Boolean) get(17);
    }

    /**
     * Setter for <code>public.pupil.morning_snack_tue</code>.
     */
    public void setMorningSnackTue(Boolean value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.pupil.morning_snack_tue</code>.
     */
    public Boolean getMorningSnackTue() {
        return (Boolean) get(18);
    }

    /**
     * Setter for <code>public.pupil.morning_snack_wed</code>.
     */
    public void setMorningSnackWed(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.pupil.morning_snack_wed</code>.
     */
    public Boolean getMorningSnackWed() {
        return (Boolean) get(19);
    }

    /**
     * Setter for <code>public.pupil.morning_snack_thu</code>.
     */
    public void setMorningSnackThu(Boolean value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.pupil.morning_snack_thu</code>.
     */
    public Boolean getMorningSnackThu() {
        return (Boolean) get(20);
    }

    /**
     * Setter for <code>public.pupil.morning_snack_fri</code>.
     */
    public void setMorningSnackFri(Boolean value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.pupil.morning_snack_fri</code>.
     */
    public Boolean getMorningSnackFri() {
        return (Boolean) get(21);
    }

    /**
     * Setter for <code>public.pupil.afternoon_snack_mon</code>.
     */
    public void setAfternoonSnackMon(Boolean value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.pupil.afternoon_snack_mon</code>.
     */
    public Boolean getAfternoonSnackMon() {
        return (Boolean) get(22);
    }

    /**
     * Setter for <code>public.pupil.afternoon_snack_tue</code>.
     */
    public void setAfternoonSnackTue(Boolean value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.pupil.afternoon_snack_tue</code>.
     */
    public Boolean getAfternoonSnackTue() {
        return (Boolean) get(23);
    }

    /**
     * Setter for <code>public.pupil.afternoon_snack_wed</code>.
     */
    public void setAfternoonSnackWed(Boolean value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.pupil.afternoon_snack_wed</code>.
     */
    public Boolean getAfternoonSnackWed() {
        return (Boolean) get(24);
    }

    /**
     * Setter for <code>public.pupil.afternoon_snack_thu</code>.
     */
    public void setAfternoonSnackThu(Boolean value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.pupil.afternoon_snack_thu</code>.
     */
    public Boolean getAfternoonSnackThu() {
        return (Boolean) get(25);
    }

    /**
     * Setter for <code>public.pupil.afternoon_snack_fri</code>.
     */
    public void setAfternoonSnackFri(Boolean value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.pupil.afternoon_snack_fri</code>.
     */
    public Boolean getAfternoonSnackFri() {
        return (Boolean) get(26);
    }

    /**
     * Setter for <code>public.pupil.lunch_mon</code>.
     */
    public void setLunchMon(Boolean value) {
        set(27, value);
    }

    /**
     * Getter for <code>public.pupil.lunch_mon</code>.
     */
    public Boolean getLunchMon() {
        return (Boolean) get(27);
    }

    /**
     * Setter for <code>public.pupil.lunch_tue</code>.
     */
    public void setLunchTue(Boolean value) {
        set(28, value);
    }

    /**
     * Getter for <code>public.pupil.lunch_tue</code>.
     */
    public Boolean getLunchTue() {
        return (Boolean) get(28);
    }

    /**
     * Setter for <code>public.pupil.lunch_wed</code>.
     */
    public void setLunchWed(Boolean value) {
        set(29, value);
    }

    /**
     * Getter for <code>public.pupil.lunch_wed</code>.
     */
    public Boolean getLunchWed() {
        return (Boolean) get(29);
    }

    /**
     * Setter for <code>public.pupil.lunch_thu</code>.
     */
    public void setLunchThu(Boolean value) {
        set(30, value);
    }

    /**
     * Getter for <code>public.pupil.lunch_thu</code>.
     */
    public Boolean getLunchThu() {
        return (Boolean) get(30);
    }

    /**
     * Setter for <code>public.pupil.lunch_fri</code>.
     */
    public void setLunchFri(Boolean value) {
        set(31, value);
    }

    /**
     * Getter for <code>public.pupil.lunch_fri</code>.
     */
    public Boolean getLunchFri() {
        return (Boolean) get(31);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PupilRecord
     */
    public PupilRecord() {
        super(Pupil.PUPIL);
    }

    /**
     * Create a detached, initialised PupilRecord
     */
    public PupilRecord(Long id, String pupilGroup, String accessCode, Boolean extendedStay, Short leaveMon, Short leaveTue, Short leaveWed, Short leaveThu, Short leaveFri, OffsetDateTime lastLogin, String[] emails, Boolean welcomeEmailSent, String firstName, String lastName, Boolean canLeaveAlone, Short morningCareArrival, Boolean orderTextbooks, Boolean morningSnackMon, Boolean morningSnackTue, Boolean morningSnackWed, Boolean morningSnackThu, Boolean morningSnackFri, Boolean afternoonSnackMon, Boolean afternoonSnackTue, Boolean afternoonSnackWed, Boolean afternoonSnackThu, Boolean afternoonSnackFri, Boolean lunchMon, Boolean lunchTue, Boolean lunchWed, Boolean lunchThu, Boolean lunchFri) {
        super(Pupil.PUPIL);

        set(0, id);
        set(1, pupilGroup);
        set(2, accessCode);
        set(3, extendedStay);
        set(4, leaveMon);
        set(5, leaveTue);
        set(6, leaveWed);
        set(7, leaveThu);
        set(8, leaveFri);
        set(9, lastLogin);
        set(10, emails);
        set(11, welcomeEmailSent);
        set(12, firstName);
        set(13, lastName);
        set(14, canLeaveAlone);
        set(15, morningCareArrival);
        set(16, orderTextbooks);
        set(17, morningSnackMon);
        set(18, morningSnackTue);
        set(19, morningSnackWed);
        set(20, morningSnackThu);
        set(21, morningSnackFri);
        set(22, afternoonSnackMon);
        set(23, afternoonSnackTue);
        set(24, afternoonSnackWed);
        set(25, afternoonSnackThu);
        set(26, afternoonSnackFri);
        set(27, lunchMon);
        set(28, lunchTue);
        set(29, lunchWed);
        set(30, lunchThu);
        set(31, lunchFri);
    }
}
