/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db.tables.records;


import java.time.OffsetDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;

import si.francebevk.db.tables.Pupil;


/**
 * Contains a single pupil
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PupilRecord extends UpdatableRecordImpl<PupilRecord> implements Record17<Long, String, String, Boolean, Short, Short, Short, Short, Short, OffsetDateTime, String[], Boolean, String, String, Boolean, Short, Boolean> {

    private static final long serialVersionUID = 2074866742;

    /**
     * Setter for <code>public.pupil.id</code>. The pupil's unique ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.pupil.id</code>. The pupil's unique ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.pupil.pupil_group</code>. The pupil's class
     */
    public void setPupilGroup(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.pupil.pupil_group</code>. The pupil's class
     */
    public String getPupilGroup() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.pupil.access_code</code>. The pupil's access code required to access their profile
     */
    public void setAccessCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.pupil.access_code</code>. The pupil's access code required to access their profile
     */
    public String getAccessCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.pupil.extended_stay</code>. Indicates choice for pupil's inclusion in extended stay
     */
    public void setExtendedStay(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.pupil.extended_stay</code>. Indicates choice for pupil's inclusion in extended stay
     */
    public Boolean getExtendedStay() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.pupil.leave_mon</code>. Indicates the minutes of day at which pupil will leave school on monday (null means student is not participating on that day)
     */
    public void setLeaveMon(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.pupil.leave_mon</code>. Indicates the minutes of day at which pupil will leave school on monday (null means student is not participating on that day)
     */
    public Short getLeaveMon() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.pupil.leave_tue</code>. Indicates the minutes of day at which pupil will leave school on tuesday (null means student is not participating on that day)
     */
    public void setLeaveTue(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.pupil.leave_tue</code>. Indicates the minutes of day at which pupil will leave school on tuesday (null means student is not participating on that day)
     */
    public Short getLeaveTue() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.pupil.leave_wed</code>. Indicates the minutes of day at which pupil will leave school on wednesday (null means student is not participating on that day)
     */
    public void setLeaveWed(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.pupil.leave_wed</code>. Indicates the minutes of day at which pupil will leave school on wednesday (null means student is not participating on that day)
     */
    public Short getLeaveWed() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.pupil.leave_thu</code>. Indicates the minutes of day at which pupil will leave school on thursday (null means student is not participating on that day)
     */
    public void setLeaveThu(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.pupil.leave_thu</code>. Indicates the minutes of day at which pupil will leave school on thursday (null means student is not participating on that day)
     */
    public Short getLeaveThu() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>public.pupil.leave_fri</code>. Indicates the minutes of day at which pupil will leave school on friday (null means student is not participating on that day)
     */
    public void setLeaveFri(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.pupil.leave_fri</code>. Indicates the minutes of day at which pupil will leave school on friday (null means student is not participating on that day)
     */
    public Short getLeaveFri() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>public.pupil.last_login</code>.
     */
    public void setLastLogin(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.pupil.last_login</code>.
     */
    public OffsetDateTime getLastLogin() {
        return (OffsetDateTime) get(9);
    }

    /**
     * Setter for <code>public.pupil.emails</code>. All the emails to which messages for this pupil should be sent
     */
    public void setEmails(String... value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.pupil.emails</code>. All the emails to which messages for this pupil should be sent
     */
    public String[] getEmails() {
        return (String[]) get(10);
    }

    /**
     * Setter for <code>public.pupil.welcome_email_sent</code>. Set to true once an email was successfuly sent to this pupil
     */
    public void setWelcomeEmailSent(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.pupil.welcome_email_sent</code>. Set to true once an email was successfuly sent to this pupil
     */
    public Boolean getWelcomeEmailSent() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.pupil.first_name</code>. First name of the pupil
     */
    public void setFirstName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.pupil.first_name</code>. First name of the pupil
     */
    public String getFirstName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.pupil.last_name</code>. Last name of the pupil
     */
    public void setLastName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.pupil.last_name</code>. Last name of the pupil
     */
    public String getLastName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.pupil.can_leave_alone</code>. If true, younger pupils can still leave school without an escort
     */
    public void setCanLeaveAlone(Boolean value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.pupil.can_leave_alone</code>. If true, younger pupils can still leave school without an escort
     */
    public Boolean getCanLeaveAlone() {
        return (Boolean) get(14);
    }

    /**
     * Setter for <code>public.pupil.morning_care_arrival</code>. If not null then the pupil will arrive into morning care at this time
     */
    public void setMorningCareArrival(Short value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.pupil.morning_care_arrival</code>. If not null then the pupil will arrive into morning care at this time
     */
    public Short getMorningCareArrival() {
        return (Short) get(15);
    }

    /**
     * Setter for <code>public.pupil.order_textbooks</code>. Did the pupil order textbooks from the school's textbook fund?
     */
    public void setOrderTextbooks(Boolean value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.pupil.order_textbooks</code>. Did the pupil order textbooks from the school's textbook fund?
     */
    public Boolean getOrderTextbooks() {
        return (Boolean) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, String, String, Boolean, Short, Short, Short, Short, Short, OffsetDateTime, String[], Boolean, String, String, Boolean, Short, Boolean> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row17<Long, String, String, Boolean, Short, Short, Short, Short, Short, OffsetDateTime, String[], Boolean, String, String, Boolean, Short, Boolean> valuesRow() {
        return (Row17) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Pupil.PUPIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Pupil.PUPIL.PUPIL_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Pupil.PUPIL.ACCESS_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Pupil.PUPIL.EXTENDED_STAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return Pupil.PUPIL.LEAVE_MON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field6() {
        return Pupil.PUPIL.LEAVE_TUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field7() {
        return Pupil.PUPIL.LEAVE_WED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field8() {
        return Pupil.PUPIL.LEAVE_THU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field9() {
        return Pupil.PUPIL.LEAVE_FRI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OffsetDateTime> field10() {
        return Pupil.PUPIL.LAST_LOGIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field11() {
        return Pupil.PUPIL.EMAILS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return Pupil.PUPIL.WELCOME_EMAIL_SENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Pupil.PUPIL.FIRST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Pupil.PUPIL.LAST_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field15() {
        return Pupil.PUPIL.CAN_LEAVE_ALONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field16() {
        return Pupil.PUPIL.MORNING_CARE_ARRIVAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field17() {
        return Pupil.PUPIL.ORDER_TEXTBOOKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPupilGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAccessCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getExtendedStay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component5() {
        return getLeaveMon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component6() {
        return getLeaveTue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component7() {
        return getLeaveWed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component8() {
        return getLeaveThu();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component9() {
        return getLeaveFri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime component10() {
        return getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component11() {
        return getEmails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getWelcomeEmailSent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component15() {
        return getCanLeaveAlone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short component16() {
        return getMorningCareArrival();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component17() {
        return getOrderTextbooks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPupilGroup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAccessCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getExtendedStay();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getLeaveMon();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value6() {
        return getLeaveTue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value7() {
        return getLeaveWed();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value8() {
        return getLeaveThu();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value9() {
        return getLeaveFri();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OffsetDateTime value10() {
        return getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value11() {
        return getEmails();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getWelcomeEmailSent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getFirstName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getLastName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value15() {
        return getCanLeaveAlone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value16() {
        return getMorningCareArrival();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value17() {
        return getOrderTextbooks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value2(String value) {
        setPupilGroup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value3(String value) {
        setAccessCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value4(Boolean value) {
        setExtendedStay(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value5(Short value) {
        setLeaveMon(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value6(Short value) {
        setLeaveTue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value7(Short value) {
        setLeaveWed(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value8(Short value) {
        setLeaveThu(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value9(Short value) {
        setLeaveFri(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value10(OffsetDateTime value) {
        setLastLogin(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value11(String... value) {
        setEmails(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value12(Boolean value) {
        setWelcomeEmailSent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value13(String value) {
        setFirstName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value14(String value) {
        setLastName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value15(Boolean value) {
        setCanLeaveAlone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value16(Short value) {
        setMorningCareArrival(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord value17(Boolean value) {
        setOrderTextbooks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PupilRecord values(Long value1, String value2, String value3, Boolean value4, Short value5, Short value6, Short value7, Short value8, Short value9, OffsetDateTime value10, String[] value11, Boolean value12, String value13, String value14, Boolean value15, Short value16, Boolean value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PupilRecord
     */
    public PupilRecord() {
        super(Pupil.PUPIL);
    }

    /**
     * Create a detached, initialised PupilRecord
     */
    public PupilRecord(Long id, String pupilGroup, String accessCode, Boolean extendedStay, Short leaveMon, Short leaveTue, Short leaveWed, Short leaveThu, Short leaveFri, OffsetDateTime lastLogin, String[] emails, Boolean welcomeEmailSent, String firstName, String lastName, Boolean canLeaveAlone, Short morningCareArrival, Boolean orderTextbooks) {
        super(Pupil.PUPIL);

        set(0, id);
        set(1, pupilGroup);
        set(2, accessCode);
        set(3, extendedStay);
        set(4, leaveMon);
        set(5, leaveTue);
        set(6, leaveWed);
        set(7, leaveThu);
        set(8, leaveFri);
        set(9, lastLogin);
        set(10, emails);
        set(11, welcomeEmailSent);
        set(12, firstName);
        set(13, lastName);
        set(14, canLeaveAlone);
        set(15, morningCareArrival);
        set(16, orderTextbooks);
    }
}
