/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import si.francebevk.db.Public;
import si.francebevk.db.enums.DayOfWeek;
import si.francebevk.db.tables.records.ActivitySlotsRecord;


/**
 * All the various slots belonging to activities
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivitySlots extends TableImpl<ActivitySlotsRecord> {

    private static final long serialVersionUID = 1425908373;

    /**
     * The reference instance of <code>public.activity_slots</code>
     */
    public static final ActivitySlots ACTIVITY_SLOTS = new ActivitySlots();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActivitySlotsRecord> getRecordType() {
        return ActivitySlotsRecord.class;
    }

    /**
     * The column <code>public.activity_slots.activity_id</code>.
     */
    public final TableField<ActivitySlotsRecord, Long> ACTIVITY_ID = createField("activity_id", org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.activity_slots.day</code>.
     */
    public final TableField<ActivitySlotsRecord, DayOfWeek> DAY = createField("day", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(si.francebevk.db.enums.DayOfWeek.class), this, "");

    /**
     * The column <code>public.activity_slots.start_minutes</code>.
     */
    public final TableField<ActivitySlotsRecord, Short> START_MINUTES = createField("start_minutes", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.activity_slots.end_minutes</code>.
     */
    public final TableField<ActivitySlotsRecord, Short> END_MINUTES = createField("end_minutes", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * Create a <code>public.activity_slots</code> table reference
     */
    public ActivitySlots() {
        this(DSL.name("activity_slots"), null);
    }

    /**
     * Create an aliased <code>public.activity_slots</code> table reference
     */
    public ActivitySlots(String alias) {
        this(DSL.name(alias), ACTIVITY_SLOTS);
    }

    /**
     * Create an aliased <code>public.activity_slots</code> table reference
     */
    public ActivitySlots(Name alias) {
        this(alias, ACTIVITY_SLOTS);
    }

    private ActivitySlots(Name alias, Table<ActivitySlotsRecord> aliased) {
        this(alias, aliased, null);
    }

    private ActivitySlots(Name alias, Table<ActivitySlotsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "All the various slots belonging to activities");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivitySlots as(String alias) {
        return new ActivitySlots(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ActivitySlots as(Name alias) {
        return new ActivitySlots(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivitySlots rename(String name) {
        return new ActivitySlots(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ActivitySlots rename(Name name) {
        return new ActivitySlots(name, null);
    }
}
