/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import si.francebevk.db.Public;
import si.francebevk.db.enums.DayOfWeek;
import si.francebevk.db.tables.records.DeparturesHourlyReportRecord;
import si.francebevk.db.udt.records.NamedStringsRecord;


/**
 * A review of hourly activity per-class
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DeparturesHourlyReport extends TableImpl<DeparturesHourlyReportRecord> {

    private static final long serialVersionUID = 924037056;

    /**
     * The reference instance of <code>public.departures_hourly_report</code>
     */
    public static final DeparturesHourlyReport DEPARTURES_HOURLY_REPORT = new DeparturesHourlyReport();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeparturesHourlyReportRecord> getRecordType() {
        return DeparturesHourlyReportRecord.class;
    }

    /**
     * The column <code>public.departures_hourly_report.pupil_group</code>.
     */
    public final TableField<DeparturesHourlyReportRecord, String> PUPIL_GROUP = createField("pupil_group", org.jooq.impl.SQLDataType.VARCHAR(2), this, "");

    /**
     * The column <code>public.departures_hourly_report.day</code>.
     */
    public final TableField<DeparturesHourlyReportRecord, DayOfWeek> DAY = createField("day", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(si.francebevk.db.enums.DayOfWeek.class), this, "");

    /**
     * The column <code>public.departures_hourly_report.leave_minutes</code>.
     */
    public final TableField<DeparturesHourlyReportRecord, Short> LEAVE_MINUTES = createField("leave_minutes", org.jooq.impl.SQLDataType.SMALLINT, this, "");

    /**
     * The column <code>public.departures_hourly_report.still_here</code>.
     */
    public final TableField<DeparturesHourlyReportRecord, String[]> STILL_HERE = createField("still_here", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), this, "");

    /**
     * The column <code>public.departures_hourly_report.leave</code>.
     */
    public final TableField<DeparturesHourlyReportRecord, String[]> LEAVE = createField("leave", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), this, "");

    /**
     * The column <code>public.departures_hourly_report.at_activities</code>.
     */
    public final TableField<DeparturesHourlyReportRecord, NamedStringsRecord[]> AT_ACTIVITIES = createField("at_activities", si.francebevk.db.udt.NamedStrings.NAMED_STRINGS.getDataType().getArrayDataType(), this, "");

    /**
     * Create a <code>public.departures_hourly_report</code> table reference
     */
    public DeparturesHourlyReport() {
        this(DSL.name("departures_hourly_report"), null);
    }

    /**
     * Create an aliased <code>public.departures_hourly_report</code> table reference
     */
    public DeparturesHourlyReport(String alias) {
        this(DSL.name(alias), DEPARTURES_HOURLY_REPORT);
    }

    /**
     * Create an aliased <code>public.departures_hourly_report</code> table reference
     */
    public DeparturesHourlyReport(Name alias) {
        this(alias, DEPARTURES_HOURLY_REPORT);
    }

    private DeparturesHourlyReport(Name alias, Table<DeparturesHourlyReportRecord> aliased) {
        this(alias, aliased, null);
    }

    private DeparturesHourlyReport(Name alias, Table<DeparturesHourlyReportRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "A review of hourly activity per-class");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeparturesHourlyReport as(String alias) {
        return new DeparturesHourlyReport(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DeparturesHourlyReport as(Name alias) {
        return new DeparturesHourlyReport(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DeparturesHourlyReport rename(String name) {
        return new DeparturesHourlyReport(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DeparturesHourlyReport rename(Name name) {
        return new DeparturesHourlyReport(name, null);
    }
}
