/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db.udt.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UDTRecordImpl;

import si.francebevk.db.udt.NamedStrings;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NamedStringsRecord extends UDTRecordImpl<NamedStringsRecord> implements Record2<String, String[]> {

    private static final long serialVersionUID = -428028173;

    /**
     * Setter for <code>public.named_strings.name</code>.
     */
    public void setName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.named_strings.name</code>.
     */
    public String getName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.named_strings.strings</code>.
     */
    public void setStrings(String... value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.named_strings.strings</code>.
     */
    public String[] getStrings() {
        return (String[]) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String[]> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return NamedStrings.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String[]> field2() {
        return NamedStrings.STRINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] component2() {
        return getStrings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String[] value2() {
        return getStrings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NamedStringsRecord value1(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NamedStringsRecord value2(String... value) {
        setStrings(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NamedStringsRecord values(String value1, String[] value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NamedStringsRecord
     */
    public NamedStringsRecord() {
        super(NamedStrings.NAMED_STRINGS);
    }

    /**
     * Create a detached, initialised NamedStringsRecord
     */
    public NamedStringsRecord(String name, String[] strings) {
        super(NamedStrings.NAMED_STRINGS);

        set(0, name);
        set(1, strings);
    }
}
