/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db.udt;


import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.UDTField;
import org.jooq.impl.UDTImpl;

import si.francebevk.db.Public;
import si.francebevk.db.udt.records.NamedStringsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NamedStrings extends UDTImpl<NamedStringsRecord> {

    private static final long serialVersionUID = 766945725;

    /**
     * The reference instance of <code>public.named_strings</code>
     */
    public static final NamedStrings NAMED_STRINGS = new NamedStrings();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<NamedStringsRecord> getRecordType() {
        return NamedStringsRecord.class;
    }

    /**
     * The attribute <code>public.named_strings.name</code>.
     */
    public static final UDTField<NamedStringsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, NAMED_STRINGS, "");

    /**
     * The attribute <code>public.named_strings.strings</code>.
     */
    public static final UDTField<NamedStringsRecord, String[]> STRINGS = createField("strings", org.jooq.impl.SQLDataType.CLOB.getArrayDataType(), NAMED_STRINGS, "");

    /**
     * No further instances allowed
     */
    private NamedStrings() {
        super("named_strings", null, null, false);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }
}
