/*
 * This file is generated by jOOQ.
*/
package si.francebevk.db.udt;


import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.UDTField;
import org.jooq.impl.UDTImpl;

import si.francebevk.db.Public;
import si.francebevk.db.enums.DayOfWeek;
import si.francebevk.db.udt.records.TimeSlotRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeSlot extends UDTImpl<TimeSlotRecord> {

    private static final long serialVersionUID = 2059031070;

    /**
     * The reference instance of <code>public.time_slot</code>
     */
    public static final TimeSlot TIME_SLOT = new TimeSlot();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TimeSlotRecord> getRecordType() {
        return TimeSlotRecord.class;
    }

    /**
     * The attribute <code>public.time_slot.day</code>.
     */
    public static final UDTField<TimeSlotRecord, DayOfWeek> DAY = createField("day", org.jooq.util.postgres.PostgresDataType.VARCHAR.asEnumDataType(si.francebevk.db.enums.DayOfWeek.class), TIME_SLOT, "");

    /**
     * The attribute <code>public.time_slot.start_minutes</code>.
     */
    public static final UDTField<TimeSlotRecord, Short> START_MINUTES = createField("start_minutes", org.jooq.impl.SQLDataType.SMALLINT, TIME_SLOT, "");

    /**
     * The attribute <code>public.time_slot.end_minutes</code>.
     */
    public static final UDTField<TimeSlotRecord, Short> END_MINUTES = createField("end_minutes", org.jooq.impl.SQLDataType.SMALLINT, TIME_SLOT, "");

    /**
     * No further instances allowed
     */
    private TimeSlot() {
        super("time_slot", null, null, false);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }
}
